# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5b3063768a3be564548a81a07aebd1339da87d90c1a9177f6264d9b54994bab3b5813c88715f296f5e80c62862364200f72206be8796fb52361caa8d4639a6

test:
  secret_key_base: 9e5e2723fbb9c25df2e99a59625cc11e0a4de88d258cc57614dac73debffb8e71c3cb489546a94985322c613c5396034967a8df409cbad1102cdabd9f7c17b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
